[project]
name = 'scredence'
description = 'Bitcoin-anchored verification for internships, NYSC & professional service'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.service-verification]
path = 'contracts/service-verification.clar'
clarity_version = 3
epoch = 'latest'

[contracts.traits]
path = 'contracts/traits.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
