[project]
name = 'scredence'
description = 'Bitcoin-anchored verification for internships, NYSC & professional service'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.scredence-verification-alpha]
path = 'contracts/scredence-verification-alpha.clar'
clarity_version = 4
epoch = '3.3'

[contracts.scredence-traits-alpha]
path = 'contracts/scredence-traits-alpha.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
